#!/bin/bash

echo "Version Info" > /tmp/version.txt
# output version.txt which is generated by github actions for release
cat version.txt >> /tmp/version.txt
# output git info if it is build on git repo
if git status > /dev/null 2>&1; then
    git describe --all --long --dirty >> /tmp/version.txt
    git diff --shortstat | tr ' ' '_' | tr ',' '_' >> /tmp/version.txt
fi

# convert /tmp/version.txt to version.h
echo -n "const char *VERSION = \"" > version.h
while IFS= read -r line; do
    echo -n "$line\n" | sed 's/"/\\"/g' >> version.h
done < /tmp/version.txt
echo "\";" >> version.h
