---
name: Arduino_CI

on:
  push:
    branches: [ master ]

jobs:
  arduino_ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        type: [GT, GTM]
    steps:
      - uses: actions/checkout@v3
      - uses: arduino/compile-sketches@v1
        with:
          sketch-paths: |
            - .
          cli-compile-flags: |
            - --build-property
            - build.extra_flags=-D${{ matrix.type }}
          fqbn: "arduino:avr:mega:cpu=atmega2560"
          libraries: |
            - name: Rosserial Arduino Library
              version: 0.7.9
            - name: Adafruit BNO055
            - name: Adafruit BMP280 Library
            - name: Adafruit MPR121
            - name: arduino-timer
