---
name: Arduino_CI

on:
  push:
    branches: [ master ]

jobs:
  arduino_ci:
    needs: cpplint
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        type: [GT, GTM]
    steps:
      - uses: actions/checkout@v3
      - uses: arduino/compile-sketches@v1
        with:
          sketch-paths: |
            - .
          cli-compile-flags: |
            - --build-property
            - build.extra_flags=-D${{ matrix.type }}
          fqbn: "arduino:avr:mega:cpu=atmega2560"
          libraries: |
            - name: Rosserial Arduino Library
              version: 0.7.9
            - name: Adafruit BNO055
            - name: Adafruit BMP280 Library
            - name: Adafruit MPR121
            - name: arduino-timer

  cpplint:
    runs-on: ubuntu-latest
    steps:
      - name: Setup cpplint
        run: |
          sudo apt install python3-pip
          pip install cpplint
      - uses: actions/checkout@v3
      - name: Run cpplint
        run: |
          cpplint --recursive .

  uncrustify:
    runs-on: ubuntu-latest
    steps:
      - name: Setup uncrustify
        run: |
          sudo apt-get install -y uncrustify
      - uses: actions/checkout@v3
      - name: Run uncrustify
        run: |
          ls *.ino *.h *.cpp | uncrustify -c code_style.cfg --check -F -
